---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-yandexcertificatemanager
  namespace: external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store-yandexcertificatemanager
    kind: SecretStore
  target:
    name: certificate-secret
  data:
    - secretKey: tls.crt
      remoteRef:
        key: 'e6q5d41o9f2t6ujg03pt'
        property: chain
    - secretKey: tls.key
      remoteRef:
        key: 'e6q5d41o9f2t6ujg03pt'
        property: privateKey
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-yandexlockbox
  namespace: external-secret
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secret-store-yandexlockbox
    kind: SecretStore
  target:
    name: lockbox-secret
  data:
    - secretKey: password
      remoteRef:
        key: 'e6q9d41o9f2t6ujg02pt'
        property: testkey
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-vault1
  namespace: external-secret
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secret-store-vault-devops-approle
    kind: ClusterSecretStore
  target:
    name: vault-secret-one-key
  data:
  - secretKey: grafana
    remoteRef:
      key: dev/grafana-infra
      property: url
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-vault2
  namespace: external-secret
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secret-store-vault-devops-approle
    kind: ClusterSecretStore
  target:
    name: vault-secret-all-key
  dataFrom:
  - extract:
      key: dev/grafana-infra